services:
  bot:
    build: .
    container_name: bot-financas
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
      - postgres
    networks:
      - financas_network

  mongo:
    image: mongo:7
    container_name: mongo-financas
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${ADMIN_PASSWORD}
      MONGO_INITDB_DATABASE: financas_db
    volumes:
      - mongo_data:/data/db
    networks:
      - financas_network

  postgres:
    image: postgres:16
    container_name: postgres-financas
    restart: always
    ports:
      - "5434:5434"
    environment:
      POSTGRES_USER: ${ADMIN_USER}
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
      POSTGRES_DB: financas_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - financas_network

volumes:
  mongo_data:
  postgres_data:

networks:
  financas_network:
    driver: bridge